//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public Nullable<int> Tickets { get; set; }
        public System.DateTime Date { get; set; }
        public string Venue { get; set; }
        public string Description { get; set; }
        public string Poster { get; set; }
        public int Status { get; set; }
        public string DisapproveComments { get; set; }
        public string ContactEmail { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
